apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://13.232.127.27:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
users:
- name: default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrRENDQVRlZ0F3SUJBZ0lJWWd0UVRKbXdaYkF3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOemczTWpNek9UazRNQjRYRFRJMk1EZ3lNREV5TlRNeE9Gb1hEVEkzTURneQpNREV5TlRNeE9Gb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFRDJTbjdpay9ZZHlPOEYKVjhPWHg4WS83c2hWNy9qamlJUG9oUjVZTFRzTUpMdDc3dWtRUTZ0eEFoK1VYMGZVSkNIQXZ3REcyYTdzUGhiQgovaEZGUEtLalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUUZ3SnJKOG1PdlB4VXZSbFJTZWZYU3lBN1Q5REFLQmdncWhrak9QUVFEQWdOSEFEQkUKQWlCeXpUemZ0MHJFVnJFWVA1Rk81ZHFLdWtTd0lLejQrbU4yeGZlaGtMSFJCZ0lnTm1QZXRrYy9XNCtvRVhjWgpSZkZXY21EUkJ3ek5NR0VWTkdSSWhnT1F2aGs9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUzT0RjeU16TTVPVGd3SGhjTk1qWXdPREl3TVRJMU16RTRXaGNOTXpZd09ERTNNVEkxTXpFNApXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUzT0RjeU16TTVPVGd3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQ1U0cmFYNnZ3cGhFV3hRYWF0VCt2V0Vpcml1TnVPR2ZuTXpzRHliekcKR2NXZHVpKzh0K0xSNFFCcHZiZTduSFYwVHpsV3pSMXB4UFhCYjQwRDd2aDZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUJjQ2F5Zkpqcno4VkwwWlVVbm4xCjBzZ08wL1F3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU1pY2pwN1pwbG1aMG5oU3FuZjluTDZUUXFPeU85YzAKb1phK0g0THhQRFBRQWlBWlY3Rnhtb1NGOXpPUjl6Y1VWTzE0YjBwNzMxanFDTVBwT1B3b1E2SGlZdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUEraGZvcTlhaUNEV3o3UFYza3FpYS9Vem9RUHladkRPRGhQaGJ2ZXNMWjhvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFUVBaS2Z1S1Q5aDNJN3dWWHc1Zkh4ai91eUZYditPT0lnK2lGSGxndE93d2t1M3Z1NlJCRApxM0VDSDVSZlI5UWtJY0MvQU1iWnJ1dytGc0grRVVVOG9nPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
