# manifests/skills/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skills
  namespace: skills
  labels:
    app: skills
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skills
  template:
    metadata:
      labels:
        app: skills
        portfolio-section: skills
    spec:
      automountServiceAccountToken: false

      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: skills
          image: faizanfirdousi/portfolio-skills:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
              ephemeral-storage: "10Mi"
            limits:
              memory: "64Mi"
              cpu: "50m"
              ephemeral-storage: "20Mi"

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
