apiVersion: v1
kind: Service
metadata:
  name: skills
  namespace: skills
spec:
  selector:
    app: skills
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
