# manifests/about/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: about
  namespace: about

spec:
  selector:
    app: about

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP

  type: ClusterIP
